<a href="https://colab.research.google.com/github/seohy20251243/BDA-/blob/main/BDA6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
import pandas as pd

s= pd.Series([1,3,5,np.nan,6,8], name='first')
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
Name: first, dtype: float64

In [4]:
s.name

'first'

In [5]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [6]:
s.values

array([ 1.,  3.,  5., nan,  6.,  8.])

In [7]:
s.shape

(6,)

In [8]:
s.size

6

In [9]:
import numpy as np
import pandas as pd

s= pd.Series([1,3,5,np.nan,6,8],name='first')
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
Name: first, dtype: float64

In [10]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
Name: first, dtype: float64

In [11]:
s[1]

np.float64(3.0)

In [12]:
s[1:5]

1    3.0
2    5.0
3    NaN
4    6.0
Name: first, dtype: float64

In [16]:
import pandas as pd

pf = pd.DataFrame(data=[[25,35,8,18],
                        [18,27,10,20],
                        [1,7,17,10],
                        [12,22,9,20],
                        [22,34,8,16]],
                  index=['윤일형','강수희','홍소희','유한빈','신수빈'],
                  columns=['중간','기말','과제', '출석'])
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희   1   7  17  10
유한빈  12  22   9  20
신수빈  22  34   8  16

In [17]:
pf.loc[:,'과제']

윤일형     8
강수희    10
홍소희    17
유한빈     9
신수빈     8
Name: 과제, dtype: int64

In [18]:
pf.loc[:,'중간':'과제']

     중간  기말  과제
윤일형  25  35   8
강수희  18  27  10
홍소희   1   7  17
유한빈  12  22   9
신수빈  22  34   8

In [19]:
pf.loc[:,['기말', '출석']]

     기말  출석
윤일형  35  18
강수희  27  20
홍소희   7  10
유한빈  22  20
신수빈  34  16

In [20]:
pf.iloc[:,2]

윤일형     8
강수희    10
홍소희    17
유한빈     9
신수빈     8
Name: 과제, dtype: int64

In [21]:
pf.iloc[:,[2]]

     과제
윤일형   8
강수희  10
홍소희  17
유한빈   9
신수빈   8

In [22]:
pf.iloc[:,1:]

     기말  과제  출석
윤일형  35   8  18
강수희  27  10  20
홍소희   7  17  10
유한빈  22   9  20
신수빈  34   8  16

In [23]:
pf.at['윤일형', '기말']

np.int64(35)

In [24]:
pf.iat[1,2]

np.int64(10)

In [27]:
df=pd.DataFrame({'A':range(1,6),
                 'B':range(6,-3,-2),
                  'c':range(10,5,-1),
                  'D':range(3,-2,-1),
                  'E':['python','java','python','go','python']})
df

   A  B   c  D       E
0  1  6  10  3  python
1  2  4   9  2    java
2  3  2   8  1  python
3  4  0   7  0      go
4  5 -2   6 -1  python

In [28]:
df.query('A>B')

   A  B  c  D       E
2  3  2  8  1  python
3  4  0  7  0      go
4  5 -2  6 -1  python

In [29]:
df[df.A>df.B]

   A  B  c  D       E
2  3  2  8  1  python
3  4  0  7  0      go
4  5 -2  6 -1  python

In [32]:
df.query('c==10')

   A  B   c  D       E
0  1  6  10  3  python